### ISSUE TITLE
Rebase on official kiwix-js 2.2 release

### ISSUE THREAD

**Issue by kelson42** [DaBrown95/safe-wiki#2]
Release has been done a few days ago.

**Comment by DaBrown95** [comment]
![screen shot 2018-02-13 at 14 00 21 2](https://user-images.githubusercontent.com/11600230/36154802-7bb60f72-10ca-11e8-8765-caca0d6b5c90.png)
 As you can see I have fixed the issue in 43cccb1ae7d0a4bdd60e561944291ecd5f20abb5.

I am pretty sure that this issue only exists in SAFE Wiki. With this fixed I am now up to date with Kiwix-JS 2.2. StackOverflow ZIM files are awesome! I am going to follow this up at some point and if something needs addressed upstream I will submit a bug report and lend a hand to fix it.
